services:

  blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blue-app
    ports:
      - "5001:80"
    restart: unless-stopped

  green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green-app
    ports:
      - "5002:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: blue-green-nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - blue
      - green
    restart: unless-stopped